// SPDX-License-Identifier: Apache-2.0
// Plugin GET request string ({action, deviceId, ts, nonce} without type and supervisorId) against
// the pluginRequest vector from protocol/vectors/transport_vectors.json (generated by Go wardend:
// go test ./envelope -run TestTransportVectors -update-transport). The same file also has the wardend
// request string with the same action, deviceId, ts, and nonce: a signature for one path is not
// valid for the other (protocol/README.md, section 5.6).
import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { requestSigningString } from "../src/canonical.js";
import { deviceIdOfPublicKey, verifyEd25519 } from "../src/crypto.js";
import { StaticDeviceDirectory } from "../src/devices.js";
import { NonceCache, verifySignedRequest } from "../src/verify.js";

const tv = JSON.parse(fs.readFileSync(new URL("../../protocol/vectors/transport_vectors.json", import.meta.url), "utf8"));
const pr = tv.pluginRequest;

function ctxFor(now) {
  return {
    now,
    trustedDeviceIds: [tv.deviceId],
    tsWindowMs: 60_000,
    directory: new StaticDeviceDirectory([{ deviceId: tv.deviceId, publicKey: tv.devicePubkey }]),
    nonces: new NonceCache({ windowMs: 60_000, now: () => now }),
  };
}

test("transport_vectors pluginRequest: canonical.js builds the same string byte-for-byte", () => {
  assert.equal(deviceIdOfPublicKey(tv.devicePubkey), tv.deviceId);
  assert.equal(requestSigningString({ action: pr.action, deviceId: tv.deviceId, ts: pr.ts, nonce: pr.nonce }), pr.signingString);
  assert.ok(verifyEd25519(pr.signingString, pr.signature, tv.devicePubkey));
});

test("transport_vectors pluginRequest: verify.js accepts the vector signature, rejects the wardend string", async () => {
  const ok = await verifySignedRequest({ action: pr.action, deviceId: tv.deviceId, ts: String(pr.ts), nonce: pr.nonce, signature: pr.signature }, ctxFor(pr.ts));
  assert.equal(ok.ok, true, ok.reason);
  assert.equal(ok.deviceId, tv.deviceId);

  // wardend request with the same action, deviceId, ts, nonce: different string (type, supervisorId)
  const rq = tv.request;
  assert.equal(rq.action, pr.action);
  assert.equal(rq.ts, pr.ts);
  assert.equal(rq.nonce, pr.nonce);
  assert.notEqual(rq.signingString, pr.signingString);
  const cross = await verifySignedRequest({ action: rq.action, deviceId: tv.deviceId, ts: rq.ts, nonce: rq.nonce, signature: rq.signature }, ctxFor(rq.ts));
  assert.deepEqual(cross, { ok: false, reason: "bad_signature" });
  // and vice versa: plugin signature does not pass for the wardend string
  assert.equal(verifyEd25519(rq.signingString, pr.signature, tv.devicePubkey), false);
});

test("transport_vectors pluginRequest: signature is bound to action and nonce, nonce is one-time", async () => {
  const ctx = ctxFor(pr.ts);
  const req = { action: pr.action, deviceId: tv.deviceId, ts: pr.ts, nonce: pr.nonce, signature: pr.signature };
  assert.deepEqual(await verifySignedRequest({ ...req, action: "status" }, ctx), { ok: false, reason: "bad_signature" });
  assert.deepEqual(await verifySignedRequest({ ...req, nonce: `${pr.nonce.slice(0, -1)}c` }, ctx), { ok: false, reason: "bad_signature" });
  assert.equal((await verifySignedRequest(req, ctx)).ok, true);
  assert.deepEqual(await verifySignedRequest(req, ctx), { ok: false, reason: "nonce_reused" });
  assert.deepEqual(await verifySignedRequest(req, ctxFor(pr.ts + 60_001)), { ok: false, reason: "stale_timestamp" });
});
