// SPDX-License-Identifier: GPL-3.0-or-later
import { StyleSheet } from "react-native";
import { fonts } from "../theme";

export const styles = StyleSheet.create({
  screen: { flex: 1 },
  header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingHorizontal: 16, paddingTop: 8, paddingBottom: 4 },
  h1: { fontSize: 28, fontWeight: "800" },
  card: { borderRadius: 16, padding: 14, paddingTop: 10, marginBottom: 14 },
  row: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 6 },
  who: { flexDirection: "row", alignItems: "center", gap: 6, flexShrink: 1, marginRight: 8 },
  server: { fontSize: 15, fontWeight: "600", flexShrink: 1 },
  agent: { fontSize: 13, fontWeight: "400" },
  status: { fontSize: 13, fontWeight: "700" },
  why: { marginBottom: 4 },
  whyText: { fontSize: 14, fontWeight: "600" },
  origin: { marginTop: 2, marginBottom: 4 },
  ttlTrack: { height: 4, borderRadius: 2, marginBottom: 10, overflow: "hidden" },
  danger: { borderWidth: 1, borderRadius: 10, padding: 10, marginBottom: 10 },
  blockTitle: { fontSize: 11, fontWeight: "700", textTransform: "uppercase", letterSpacing: 0.6, marginTop: 4, marginBottom: 4 },
  summary: { fontSize: 17, lineHeight: 24 },
  mono: { fontFamily: fonts.mono },
  partRow: { flexDirection: "row", gap: 8 },
  partBar: { width: 3, borderRadius: 2 },
  partText: { flex: 1, fontSize: 15, lineHeight: 21 },
  moreChip: { alignSelf: "flex-start", borderWidth: 1, borderRadius: 12, paddingHorizontal: 10, paddingVertical: 4, marginTop: 2 },
  meta: { fontSize: 12, marginTop: 6 },
  consequence: { fontSize: 13, marginTop: 6 },
  hint: { fontSize: 12, marginTop: 8 },
  assess: { borderTopWidth: StyleSheet.hairlineWidth, marginTop: 10, paddingTop: 8 },
  assessLabel: { fontSize: 13, fontWeight: "700", marginRight: 8 },
  chipRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", marginTop: 2 },
  chip: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  chipText: { fontWeight: "800", fontSize: 13 },
  details: { borderTopWidth: StyleSheet.hairlineWidth, marginTop: 10, paddingTop: 10, gap: 4 },
  detailLine: { fontSize: 13 },
  detailBlock: { fontSize: 13, padding: 8, borderRadius: 8, backgroundColor: "rgba(127,127,127,0.12)" },
  actions: { flexDirection: "row", gap: 12, marginTop: 12 },
  bigBtn: { flex: 1, paddingVertical: 16, paddingHorizontal: 8, borderRadius: 14, alignItems: "center", justifyContent: "center" },
  bigBtnText: { fontSize: 18, fontWeight: "700", textAlign: "center" },
  holdBtn: { borderWidth: 2, backgroundColor: "transparent", overflow: "hidden", paddingVertical: 10, minHeight: 60 },
  holdFill: { position: "absolute", left: 0, top: 0, bottom: 0, overflow: "hidden" },
  holdInverse: { position: "absolute", left: 0, top: 0, alignItems: "center", justifyContent: "center", paddingHorizontal: 8 },
  empty: { flex: 1, alignItems: "center", justifyContent: "center", paddingTop: 120, gap: 8 },
  emptyTitle: { fontSize: 20, fontWeight: "700" },
  emptyHint: { fontSize: 14, textAlign: "center", paddingHorizontal: 24 },
  missed: { borderWidth: 1, borderRadius: 14, padding: 12, marginBottom: 14 },
  snack: { position: "absolute", left: 16, right: 16, bottom: 16, borderWidth: 1, borderRadius: 12, elevation: 6 },
  snackInner: { minHeight: 48, justifyContent: "center", paddingHorizontal: 14, paddingVertical: 12 },
});
