// SPDX-License-Identifier: AGPL-3.0-or-later

package envelope

import (
	"crypto/ecdsa"
	"crypto/ed25519"
	"crypto/elliptic"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"flag"
	"math/big"
	"os"
	"path/filepath"
	"testing"
	"time"
)

var updateES256 = flag.Bool("update-es256", false, "regenerate protocol/vectors/es256_vectors.json")

// Vector key: the RFC 6979 A.2.5 test P-256 key (public, not a secret).
const es256VectorScalar = "c9afa9d845ba75166b5c215767b1d6934e50c3db36e89b127b8a622b120f6721"

func es256VectorKey(t *testing.T) *ecdsa.PrivateKey {
	d, _ := hex.DecodeString(es256VectorScalar)
	k, err := ecdsa.ParseRawPrivateKey(elliptic.P256(), d)
	if err != nil {
		t.Fatal(err)
	}
	return k
}

// buildES256Vectors builds the es256-device cross-fixture (Apple Watch): key, deviceId,
// pairing/ticket/request/body-request signing strings, raw and DER signatures.
// ECDSA is deterministic here (RFC 6979) so the file is reproducible byte-for-byte;
// Secure Enclave uses random k; clients verify signing strings and check signatures.
func buildES256Vectors(t *testing.T) map[string]any {
	priv := es256VectorKey(t)
	key := ES256Key(&priv.PublicKey)
	did := key.ID()
	supSeed, _ := hex.DecodeString("4ccd089b28ff96da9db6c346ec114e0f5b8a319f35aba624da8cf6ed4fb8a6fb")
	sup := ed25519.NewKeyFromSeed(supSeed)
	sid := DeviceID(sup.Public().(ed25519.PublicKey))
	sigs := func(msg []byte) map[string]any {
		der, err := SignES256DER(priv, msg)
		if err != nil {
			t.Fatal(err)
		}
		return map[string]any{"signatureRaw": SignES256(priv, msg), "signatureDER": B64URL(der)}
	}
	const ts, nonce = int64(1790447985039), "5b8e2f0a-1c3d-4e5f-8a9b-0c1d2e3f4a5b"

	pp := PairPayload{Code: "K7Q4M2XD", DeviceID: did, Pubkey: key.B64(), Alg: AlgES256, Name: "Apple Watch", SupervisorID: sid, Ts: ts, Nonce: "0f1e2d3c-4b5a-4968-8776-655443322110"}
	pair, _ := PairSigningString(pp)
	pairV := map[string]any{"payload": pp, "signingString": string(pair), "fingerprint": Fingerprint(did)}
	for k, v := range sigs(pair) {
		pairV[k] = v
	}

	digest := "4b2e5f0c1a9d8e7f6a5b4c3d2e1f00112233445566778899aabbccddeeff0011"
	var tickets []map[string]any
	for _, dec := range []string{"allow", "deny"} {
		p := DecisionPayload{Type: TicketExec, SupervisorID: sid, ID: PendingID(digest), Digest: digest, Decision: dec, Ts: "1790447985039", Nonce: "7f0c9a2e-6b1d-4c3e-8f5a-1b2c3d4e5f6" + dec[:1]}
		ss, _ := SigningString(did, p)
		v := map[string]any{"name": dec, "payload": p, "signingString": string(ss)}
		for k, x := range sigs(ss) {
			v[k] = x
		}
		tickets = append(tickets, v)
	}

	req, _ := RequestSigningString(sid, "pending", did, ts, nonce)
	reqV := map[string]any{"action": "pending", "ts": ts, "nonce": nonce, "signingString": string(req)}
	for k, v := range sigs(req) {
		reqV[k] = v
	}

	body := map[string]any{"deviceId": did, "platform": "apns", "token": "7c9f3a5e0b1d2c4f6a8e9d0c1b2a3f4e5d6c7b8a9f0e1d2c3b4a5f6e7d8c9b0a",
		"topic": "com.wardenclaw.app.watchkitapp", "environment": "sandbox"}
	push, _ := RequestBodySigningString(sid, "push.register", did, ts, "9a8b7c6d-5e4f-4a3b-9c2d-1e0f9a8b7c6d", body)
	pushV := map[string]any{"action": "push.register", "ts": ts, "nonce": "9a8b7c6d-5e4f-4a3b-9c2d-1e0f9a8b7c6d", "body": body, "signingString": string(push),
		"headers": map[string]string{"X-Wardenclaw-Device": did, "X-Wardenclaw-Ts": "1790447985039", "X-Wardenclaw-Nonce": "9a8b7c6d-5e4f-4a3b-9c2d-1e0f9a8b7c6d", "X-Wardenclaw-Signature": "signatureRaw or signatureDER"}}
	for k, v := range sigs(push) {
		pushV[k] = v
	}
	pub, _ := priv.PublicKey.Bytes()
	return map[string]any{
		"note":           "generated by `go test ./envelope -run TestES256Vectors -update-es256` in daemon/; single copy in protocol/vectors/. ECDSA P-256/SHA-256, deterministic k (RFC 6979) so the file is reproducible; real devices sign with random k, so compare signing strings and verify signatures, do not compare signature bytes.",
		"alg":            AlgES256,
		"privateScalar":  es256VectorScalar,
		"publicKeySEC1":  B64URL(pub),
		"publicKeyHex":   hex.EncodeToString(pub),
		"deviceId":       did,
		"deviceIdRule":   "hex(sha256(65-byte SEC1 uncompressed public key))",
		"supervisorId":   sid,
		"pair":           pairV,
		"tickets":        tickets,
		"request":        reqV,
		"bodyRequest":    pushV,
		"signatureRules": "signature = base64url(raw r||s, 64 bytes) or base64url(DER); both high-S and low-S are accepted",
	}
}

func TestES256Vectors(t *testing.T) {
	v := buildES256Vectors(t)
	b, _ := json.MarshalIndent(v, "", "  ")
	b = append(b, '\n')
	path := filepath.FromSlash(vectorsDir + "/es256_vectors.json")
	if *updateES256 {
		if err := os.WriteFile(path, b, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	ref, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(ref) != string(b) {
		t.Fatalf("%s is stale — run with -update-es256", path)
	}
	// The file is also verified externally: key from publicKeySEC1, signatures from the file.
	var f struct {
		PublicKeySEC1 string `json:"publicKeySEC1"`
		DeviceID      string `json:"deviceId"`
		Pair          struct {
			SigningString string `json:"signingString"`
			SignatureRaw  string `json:"signatureRaw"`
			SignatureDER  string `json:"signatureDER"`
		} `json:"pair"`
		Tickets []struct {
			SigningString string `json:"signingString"`
			SignatureRaw  string `json:"signatureRaw"`
			SignatureDER  string `json:"signatureDER"`
		} `json:"tickets"`
	}
	if err := json.Unmarshal(ref, &f); err != nil {
		t.Fatal(err)
	}
	k, err := ParseDeviceKey("es256", f.PublicKeySEC1)
	if err != nil || k.ID() != f.DeviceID {
		t.Fatalf("key: %v %s", err, k.ID())
	}
	all := append([]struct {
		SigningString string `json:"signingString"`
		SignatureRaw  string `json:"signatureRaw"`
		SignatureDER  string `json:"signatureDER"`
	}{f.Pair}, f.Tickets...)
	for i, c := range all {
		if !k.Verify([]byte(c.SigningString), c.SignatureRaw) || !k.Verify([]byte(c.SigningString), c.SignatureDER) {
			t.Fatalf("case %d: signature does not verify", i)
		}
	}
	// v1 compatibility: pairing string without alg is unchanged, with alg it contains "alg":"es256"
	pp := PairPayload{Code: "C", DeviceID: "d", Pubkey: "k", Name: "n", SupervisorID: "s", Ts: 1, Nonce: "n"}
	a, _ := PairSigningString(pp)
	pp.Alg = AlgES256
	b2, _ := PairSigningString(pp)
	if string(a) != `{"code":"C","deviceId":"d","name":"n","nonce":"n","pubkey":"k","supervisorId":"s","ts":1,"type":"wardenclaw.pair.v1"}` ||
		string(b2) != `{"alg":"es256","code":"C","deviceId":"d","name":"n","nonce":"n","pubkey":"k","supervisorId":"s","ts":1,"type":"wardenclaw.pair.v1"}` {
		t.Fatalf("pair signing strings: %s / %s", a, b2)
	}
}

func TestES256TicketVerify(t *testing.T) {
	priv, _ := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	key := ES256Key(&priv.PublicKey)
	did := key.ID()
	digest := "4b2e5f0c1a9d8e7f6a5b4c3d2e1f00112233445566778899aabbccddeeff0011"
	devs := NewDevices([]TrustedDevice{{ID: did, Pubkey: key.B64(), Alg: "es256"}}, "")
	now := time.Now()
	ctx := func() VerifyCtx {
		return VerifyCtx{Now: now, TsWindow: time.Minute, SupervisorID: testSupervisorID, Devices: devs, Nonces: NewNonceCache(time.Minute), Pending: func(string) string { return digest }}
	}
	mk := func() DecisionBody {
		return SignPayloadES256(priv, ExecPayload(testSupervisorID, PendingID(digest), digest, "allow", now.UnixMilli(), NewNonce()))
	}
	// raw r||s
	b := mk()
	if r := Verify(&b, ctx()); r != "" {
		t.Fatalf("raw: %s", r)
	}
	// DER (as returned by Secure Enclave)
	b = mk()
	msg, _ := SigningString(did, b.Payload)
	der, _ := SignES256DER(priv, msg)
	b.Signature = B64URL(der)
	if r := Verify(&b, ctx()); r != "" {
		t.Fatalf("der: %s", r)
	}
	// high-S (r, n-s) is also valid: not normalized, same as Secure Enclave
	b = mk()
	raw, _ := DecodeB64URL(b.Signature)
	s := new(big.Int).SetBytes(raw[32:])
	s.Sub(elliptic.P256().Params().N, s)
	s.FillBytes(raw[32:])
	b.Signature = B64URL(raw)
	if r := Verify(&b, ctx()); r != "" {
		t.Fatalf("high-S: %s", r)
	}
	// tampered signature, swapped payload, truncated signature, garbage
	b = mk()
	raw, _ = DecodeB64URL(b.Signature)
	raw[10] ^= 1
	b.Signature = B64URL(raw)
	if r := Verify(&b, ctx()); r != "bad_signature" {
		t.Fatalf("tampered: %s", r)
	}
	b = mk()
	b.Payload.Decision = "deny"
	if r := Verify(&b, ctx()); r != "bad_signature" {
		t.Fatalf("payload swap: %s", r)
	}
	b = mk()
	b.Signature = b.Signature[:40]
	if r := Verify(&b, ctx()); r != "bad_signature" {
		t.Fatalf("short: %s", r)
	}
	// algorithm substitution: Ed25519 signature under an es256 device id
	_, ed, _ := ed25519.GenerateKey(rand.Reader)
	b = mk()
	b.Signature = B64URL(ed25519.Sign(ed, msg))
	if r := Verify(&b, ctx()); r != "bad_signature" {
		t.Fatalf("ed25519 sig for es256 device: %s", r)
	}
	// config with wrong alg for a 65-byte key, and with unknown alg
	for alg, want := range map[string]string{"ed25519": "config_pubkey_invalid", "": "config_pubkey_invalid", "rs256": "config_alg_invalid"} {
		d := NewDevices([]TrustedDevice{{ID: did, Pubkey: key.B64(), Alg: alg}}, "")
		if _, r := d.Key(did); r != want {
			t.Errorf("alg %q: %s", alg, r)
		}
	}
	// es256 key under a foreign id
	d := NewDevices([]TrustedDevice{{ID: SHA256Hex([]byte("x")), Pubkey: key.B64(), Alg: "es256"}}, "")
	if _, r := d.Key(SHA256Hex([]byte("x"))); r != "config_pubkey_invalid" {
		t.Errorf("id mismatch: %s", r)
	}
}

func TestES256KeyParsing(t *testing.T) {
	priv, _ := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	pub, _ := priv.PublicKey.Bytes()
	if _, err := ParseDeviceKey("es256", B64URL(pub)); err != nil {
		t.Fatal(err)
	}
	bad := append([]byte(nil), pub...)
	bad[64] ^= 1 // point not on the curve
	comp := append([]byte{2 + pub[64]&1}, pub[1:33]...)
	for name, b := range map[string][]byte{"off-curve": bad, "compressed": comp, "ed25519-size": pub[:32], "empty": nil} {
		if _, err := ParseDeviceKey("es256", B64URL(b)); err == nil {
			t.Errorf("%s accepted", name)
		}
	}
	if _, err := ParseDeviceKey("ed25519", B64URL(pub)); err == nil {
		t.Error("65-byte key accepted as ed25519")
	}
	if _, err := NormalizeAlg("ES384"); err == nil {
		t.Error("es384 accepted")
	}
	// DER: trailing bytes, non-canonical length
	msg := []byte("m")
	der, _ := SignES256DER(priv, msg)
	k := ES256Key(&priv.PublicKey)
	if !k.Verify(msg, B64URL(der)) || k.Verify(msg, B64URL(append(der, 0))) {
		t.Fatal("DER strictness")
	}
	if raw, err := RawES256(der); err != nil || !k.Verify(msg, B64URL(raw)) {
		t.Fatalf("RawES256: %v", err)
	}
}

func itoa(n int64) string { b, _ := json.Marshal(n); return string(b) }
