// SPDX-License-Identifier: AGPL-3.0-or-later

package envelope

import (
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/xarvel/WardenClaw/daemon/hwkey"
)

var updateHW = flag.Bool("update-hw", false, "regenerate testdata/hw_vectors.json")

// hwVector is the second-factor cross-fixture: device signing string (with and without risk),
// challenge, clientDataJSON, and clientDataHash. The app (TS) builds the same; the plugin
// verifies the device signature with risk. Device key is deterministic (seed in file).
type hwVector struct {
	Name              string          `json:"name"`
	Seed              string          `json:"seed"`
	DeviceID          string          `json:"deviceId"`
	Payload           DecisionPayload `json:"payload"`
	SigningString     string          `json:"signingString"`
	Signature         string          `json:"signature"`
	Challenge         string          `json:"challenge"` // base64url
	ClientDataJSON    string          `json:"clientDataJSON"`
	ClientDataHashHex string          `json:"clientDataHashHex"`
}

func buildHWVectors(t *testing.T) []hwVector {
	seed, _ := hex.DecodeString("9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60")
	priv := ed25519.NewKeyFromSeed(seed)
	did := DeviceID(priv.Public().(ed25519.PublicKey))
	digest := "4b2e5f0c1a9d8e7f6a5b4c3d2e1f00112233445566778899aabbccddeeff0011"
	r90 := json.Number("90")
	var out []hwVector
	for _, c := range []struct {
		name string
		p    DecisionPayload
	}{
		{"allow-no-risk", DecisionPayload{Type: TicketExec, SupervisorID: testSupervisorID, ID: PendingID(digest), Digest: digest, Decision: "allow", Ts: "1790447985039", Nonce: "7f0c9a2e-6b1d-4c3e-8f5a-1b2c3d4e5f60"}},
		{"allow-risk-90", DecisionPayload{Type: TicketExec, SupervisorID: testSupervisorID, ID: PendingID(digest), Digest: digest, Decision: "allow", Ts: "1790447985039", Nonce: "7f0c9a2e-6b1d-4c3e-8f5a-1b2c3d4e5f61", Risk: &r90}},
		// plugin tool-call ticket: different type, no supervisorId (signing string for cross-language
		// verification; second factor is not used by the plugin)
		{"tool-allow", DecisionPayload{Type: TicketTool, ID: "tc-0123456789abcdef", Digest: digest, Decision: "allow", Ts: "1790447985039", Nonce: "7f0c9a2e-6b1d-4c3e-8f5a-1b2c3d4e5f62"}},
	} {
		b := SignPayload(priv, c.p)
		ss, _ := SigningString(did, c.p)
		ch, err := HWChallenge(did, c.p)
		if err != nil {
			t.Fatal(err)
		}
		cdj := hwkey.ClientDataJSON("webauthn.get", ch)
		h := sha256.Sum256(cdj)
		out = append(out, hwVector{Name: c.name, Seed: hex.EncodeToString(seed), DeviceID: did, Payload: c.p, SigningString: string(ss),
			Signature: b.Signature, Challenge: B64URL(ch), ClientDataJSON: string(cdj), ClientDataHashHex: hex.EncodeToString(h[:])})
	}
	return out
}

func TestHWVectors(t *testing.T) {
	got := buildHWVectors(t)
	b, _ := json.MarshalIndent(map[string]any{"note": "generated by `go test ./envelope -run TestHWVectors -update-hw` in daemon/; single copy in protocol/vectors/", "cases": got}, "", "  ")
	b = append(b, '\n')
	path := filepath.FromSlash(vectorsDir + "/hw_vectors.json")
	if *updateHW {
		if err := os.WriteFile(path, b, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	ref, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(ref) != string(b) {
		t.Fatalf("%s is stale — run with -update-hw", path)
	}
	// exec ticket signing string without risk: type and supervisorId are included, risk is not
	if got[0].SigningString != `{"decision":"allow","deviceId":"`+got[0].DeviceID+`","digest":"`+got[0].Payload.Digest+`","id":"`+got[0].Payload.ID+`","nonce":"`+got[0].Payload.Nonce+`","supervisorId":"`+testSupervisorID+`","ts":1790447985039,"type":"wardenclaw.ticket.exec.v1"}` {
		t.Fatalf("exec signing string changed: %s", got[0].SigningString)
	}
}

func TestParseDecisionRiskAndHW(t *testing.T) {
	base := `{"deviceId":"` + strings.Repeat("a", 64) + `","signature":"x","payload":{"type":"wardenclaw.ticket.exec.v1","supervisorId":"` + testSupervisorID + `","id":"wd-1","digest":"` + strings.Repeat("b", 64) + `","decision":"allow","ts":1,"nonce":"12345678"%s}%s}`
	ok := []struct{ risk, hw string }{{"", ""}, {`,"risk":0`, ""}, {`,"risk":100`, `,"hw":{"credentialId":"a","clientDataJSON":"b","authenticatorData":"c","signature":"d"}`}}
	for _, c := range ok {
		if _, err := ParseDecision([]byte(fmt.Sprintf(base, c.risk, c.hw))); err != nil {
			t.Errorf("%q %q: %v", c.risk, c.hw, err)
		}
	}
	bad := []struct{ risk, hw, want string }{
		{`,"risk":101`, "", "risk_invalid"}, {`,"risk":-1`, "", "risk_invalid"}, {`,"risk":5.5`, "", "risk_invalid"}, {`,"risk":1e1`, "", "risk_invalid"},
		{"", `,"hw":{"credentialId":"a"}`, "hw_invalid"},
	}
	for _, c := range bad {
		if _, err := ParseDecision([]byte(fmt.Sprintf(base, c.risk, c.hw))); err == nil || err.Error() != c.want {
			t.Errorf("%q %q: %v, want %s", c.risk, c.hw, err, c.want)
		}
	}
}

// Signature with risk is verified, and tampering with risk breaks the signature;
// challenge depends on decision/digest/risk.
func TestRiskSignedAndChallengeBinding(t *testing.T) {
	_, priv, _ := ed25519.GenerateKey(nil)
	did := DeviceID(priv.Public().(ed25519.PublicKey))
	devs := NewDevices([]TrustedDevice{{ID: did, Pubkey: B64URL(priv.Public().(ed25519.PublicKey))}}, "")
	d := strings.Repeat("c", 64)
	r := json.Number("80")
	p := DecisionPayload{Type: TicketExec, SupervisorID: testSupervisorID, ID: PendingID(d), Digest: d, Decision: "allow", Ts: json.Number(strconv.FormatInt(NowMs(), 10)), Nonce: NewNonce(), Risk: &r}
	b := SignPayload(priv, p)
	ctx := VerifyCtx{Now: time.Now(), TsWindow: time.Minute, SupervisorID: testSupervisorID, Devices: devs, Nonces: NewNonceCache(time.Minute), Pending: func(string) string { return d }}
	if reason := Verify(&b, ctx); reason != "" {
		t.Fatal(reason)
	}
	low := json.Number("10")
	b2 := SignPayload(priv, p)
	b2.Payload.Risk = &low
	b2.Payload.Nonce = NewNonce()
	if reason := Verify(&b2, ctx); reason != "bad_signature" {
		t.Fatalf("risk tamper: %q", reason)
	}
	c1, _ := HWChallenge(did, p)
	for _, mut := range []func(q *DecisionPayload){
		func(q *DecisionPayload) { q.Digest = strings.Repeat("d", 64) },
		func(q *DecisionPayload) { q.Decision = "deny" },
		func(q *DecisionPayload) { q.Nonce = "other-nonce" },
		func(q *DecisionPayload) { q.Risk = nil },
		func(q *DecisionPayload) { q.SupervisorID = strings.Repeat("e", 64) },
		func(q *DecisionPayload) { q.Type, q.SupervisorID = TicketTool, "" },
	} {
		q := p
		mut(&q)
		c2, _ := HWChallenge(did, q)
		if string(c1) == string(c2) {
			t.Fatal("challenge not bound to payload field")
		}
	}
	// challenge != hash of the device signing string (domains are separated)
	ss, _ := SigningString(did, p)
	if h := sha256.Sum256(ss); string(h[:]) == string(c1) {
		t.Fatal("challenge must be domain-separated")
	}
}
