// SPDX-License-Identifier: AGPL-3.0-or-later

package envelope

import (
	"crypto/ed25519"
	"encoding/hex"
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"testing"
)

var updateTransport = flag.Bool("update-transport", false, "regenerate testdata/transport_vectors.json")

// buildTransportVectors builds the wardend-transport cross-fixture: request, pairing, and
// response signing strings, signatures (Ed25519 is deterministic), QR link. The app
// (wardendProto.ts) builds the same.
func buildTransportVectors(t *testing.T) map[string]any {
	devSeed, _ := hex.DecodeString("9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60")
	supSeed, _ := hex.DecodeString("4ccd089b28ff96da9db6c346ec114e0f5b8a319f35aba624da8cf6ed4fb8a6fb")
	dev := ed25519.NewKeyFromSeed(devSeed)
	sup := ed25519.NewKeyFromSeed(supSeed)
	devPub := dev.Public().(ed25519.PublicKey)
	supPub := sup.Public().(ed25519.PublicKey)
	did, sid := DeviceID(devPub), DeviceID(supPub)

	req, err := RequestSigningString(sid, "pending", did, 1790447985039, "5b8e2f0a-1c3d-4e5f-8a9b-0c1d2e3f4a5b")
	if err != nil {
		t.Fatal(err)
	}
	// GET request signing string for the gateway plugin (plugin/src/canonical.js, requestSigningString):
	// same action, deviceId, ts, and nonce but without type and supervisorId. wardend does not
	// accept it; vector is for the plugin and its other clients (protocol/README.md, section 5)
	preq, err := Canonical(map[string]any{"action": "pending", "deviceId": did, "ts": int64(1790447985039), "nonce": "5b8e2f0a-1c3d-4e5f-8a9b-0c1d2e3f4a5b"})
	if err != nil {
		t.Fatal(err)
	}
	pp := PairPayload{Code: "K7Q4M2XD", DeviceID: did, Pubkey: B64URL(devPub), Name: "Pixel «рабочий»", SupervisorID: sid, Ts: 1790447985039, Nonce: "0f1e2d3c-4b5a-4968-8776-655443322110"}
	pair, err := PairSigningString(pp)
	if err != nil {
		t.Fatal(err)
	}
	body := []byte(`{"ok":true,"host":"agent-host","note":"ок ✓ <&>"}`)
	rc := RespCtx{Action: "pending", DeviceID: did, Nonce: "5b8e2f0a-1c3d-4e5f-8a9b-0c1d2e3f4a5b"}
	resp, err := ResponseSigningString(rc, 200, body)
	if err != nil {
		t.Fatal(err)
	}
	// decide: response is bound to the ticket id and digest; ping and pre-auth rejection with the
	// same nonce (a MITM querying ping with the ticket nonce) use different strings and cannot
	// pass as a decide response
	digest := SHA256Hex([]byte("transport vector exec"))
	dc := RespCtx{Action: "decide", DeviceID: did, Nonce: "3c2b1a09-8f7e-4d6c-9b5a-4a3b2c1d0e0f", ID: "wd-" + digest[:32], Digest: digest}
	decBody := []byte(`{"decision":"deny","id":"wd-` + digest[:32] + `","ok":true}`)
	dec, err := ResponseSigningString(dc, 200, decBody)
	if err != nil {
		t.Fatal(err)
	}
	pingBody := []byte(`{"minClient":1,"now":1790447985039,"ok":true,"protocol":1,"service":"wardend","supervisorId":"` + sid + `","v":1}`)
	ping, err := PingSigningString(dc.Nonce, 200, pingBody)
	if err != nil {
		t.Fatal(err)
	}
	unBody := []byte(`{"id":"wd-` + digest[:32] + `","ok":false,"reason":"bad_signature"}`)
	un, err := UnauthSigningString("decide", 200, unBody)
	if err != nil {
		t.Fatal(err)
	}
	link := PairLink{URL: "https://wardend.example.com", Key: B64URL(supPub), Code: "K7Q4M2XD", Host: "agent-host"}
	return map[string]any{
		"note":          "generated by `go test ./envelope -run TestTransportVectors -update-transport` in daemon/; single copy in protocol/vectors/",
		"deviceSeed":    hex.EncodeToString(devSeed),
		"deviceId":      did,
		"devicePubkey":  B64URL(devPub),
		"supervisorKey": B64URL(supPub),
		"supervisorId":  sid,
		"request": map[string]any{"action": "pending", "ts": 1790447985039, "nonce": "5b8e2f0a-1c3d-4e5f-8a9b-0c1d2e3f4a5b",
			"signingString": string(req), "signature": B64URL(ed25519.Sign(dev, req))},
		"pluginRequest": map[string]any{"action": "pending", "ts": 1790447985039, "nonce": "5b8e2f0a-1c3d-4e5f-8a9b-0c1d2e3f4a5b",
			"signingString": string(preq), "signature": B64URL(ed25519.Sign(dev, preq))},
		"pair": map[string]any{"payload": pp, "signingString": string(pair), "signature": B64URL(ed25519.Sign(dev, pair)),
			"fingerprint": Fingerprint(did)},
		"response": map[string]any{"action": rc.Action, "deviceId": rc.DeviceID, "nonce": rc.Nonce, "status": 200, "body": string(body),
			"signingString": string(resp), "signature": SignResponse(sup, rc, 200, body)},
		"decideResponse": map[string]any{"action": dc.Action, "deviceId": dc.DeviceID, "nonce": dc.Nonce, "id": dc.ID, "digest": dc.Digest,
			"decision": "deny", "status": 200, "body": string(decBody), "signingString": string(dec), "signature": SignResponse(sup, dc, 200, decBody)},
		"pingResponse": map[string]any{"nonce": dc.Nonce, "status": 200, "body": string(pingBody), "signingString": string(ping),
			"signature": SignPing(sup, dc.Nonce, 200, pingBody)},
		"unauthResponse": map[string]any{"action": "decide", "status": 200, "body": string(unBody), "signingString": string(un),
			"signature": SignUnauth(sup, "decide", 200, unBody)},
		"link": map[string]any{"text": link.String(), "url": link.URL, "key": link.Key, "code": link.Code, "host": link.Host},
	}
}

func TestTransportVectors(t *testing.T) {
	v := buildTransportVectors(t)
	b, _ := json.MarshalIndent(v, "", "  ")
	b = append(b, '\n')
	path := filepath.FromSlash(vectorsDir + "/transport_vectors.json")
	if *updateTransport {
		if err := os.WriteFile(path, b, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	ref, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(ref) != string(b) {
		t.Fatalf("%s is stale — run with -update-transport", path)
	}
}

func TestPairLinkRoundTrip(t *testing.T) {
	_, priv, _ := ed25519.GenerateKey(nil)
	k := B64URL(priv.Public().(ed25519.PublicKey))
	l := PairLink{URL: "https://w.example.com/base?x=1&y=2", Key: k, Code: "ABCD2345", Host: "pi"}
	got, err := ParsePairLink(l.String())
	if err != nil || got != l {
		t.Fatalf("%v %+v", err, got)
	}
	for _, bad := range []string{"https://x", "wardenclaw://pair?v=2&url=a&key=" + k + "&code=c", "wardenclaw://pair?v=1&url=a&key=zz&code=c", "wardenclaw://pair?v=1&key=" + k + "&code=c"} {
		if _, err := ParsePairLink(bad); err == nil {
			t.Errorf("accepted %q", bad)
		}
	}
	if NormalizeCode(" abcd-2345 ") != "ABCD2345" || Fingerprint("0123456789abcdef00") != "0123 4567 89ab cdef" {
		t.Fatal("normalize/fingerprint")
	}
}

func TestResponseSignatureBinding(t *testing.T) {
	_, sup, _ := ed25519.GenerateKey(nil)
	pub := sup.Public().(ed25519.PublicKey)
	body := []byte(`{"ok":true}`)
	c := RespCtx{Action: "decide", DeviceID: "d1", Nonce: "n1", ID: "wd-1", Digest: "g1"}
	sig := SignResponse(sup, c, 200, body)
	ok := func(c RespCtx, status int, b []byte) bool {
		m, _ := ResponseSigningString(c, status, b)
		return VerifySig(pub, m, sig)
	}
	with := func(f func(*RespCtx)) RespCtx { x := c; f(&x); return x }
	if !ok(c, 200, body) || ok(c, 401, body) || ok(c, 200, []byte(`{"ok":false}`)) {
		t.Fatal("response signature must bind status and body")
	}
	for name, x := range map[string]RespCtx{
		"nonce":     with(func(x *RespCtx) { x.Nonce = "n2" }),
		"action":    with(func(x *RespCtx) { x.Action = "pending" }),
		"deviceId":  with(func(x *RespCtx) { x.DeviceID = "d2" }),
		"id":        with(func(x *RespCtx) { x.ID = "wd-2" }),
		"digest":    with(func(x *RespCtx) { x.Digest = "g2" }),
		"no ticket": with(func(x *RespCtx) { x.ID, x.Digest = "", "" }),
	} {
		if ok(x, 200, body) {
			t.Errorf("response signature must bind %s", name)
		}
	}
	// ping and pre-auth rejection are different types: neither can substitute for a request
	// response and vice versa
	ps := SignPing(sup, "n1", 200, body)
	us := SignUnauth(sup, "decide", 200, body)
	pm, _ := PingSigningString("n1", 200, body)
	um, _ := UnauthSigningString("decide", 200, body)
	rm, _ := ResponseSigningString(c, 200, body)
	if VerifySig(pub, rm, ps) || VerifySig(pub, rm, us) || VerifySig(pub, pm, sig) || VerifySig(pub, um, sig) || VerifySig(pub, pm, us) || VerifySig(pub, um, ps) {
		t.Fatal("ping, unauth and bound response strings must not be interchangeable")
	}
	if !VerifySig(pub, pm, ps) || !VerifySig(pub, um, us) {
		t.Fatal("ping/unauth signatures must verify under their own strings")
	}
}
