// SPDX-License-Identifier: AGPL-3.0-or-later

package main

// protocol/vectors/relay_vectors.json: the relay transport with fixed keys, for the app and any
// other client (protocol/README.md sections 5.3, 6, 11). The file is generated here
// (WARDEN_UPDATE_VECTORS=1 go test -run TestRelayVectors .) and then read back and checked from
// its own members only, the way another implementation would use it.

import (
	"bytes"
	"crypto/ecdh"
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"os"
	"strconv"
	"testing"

	"github.com/xarvel/WardenClaw/daemon/envelope"
	"github.com/xarvel/WardenClaw/daemon/relaylink"
)

const relayVectorsPath = "../protocol/vectors/relay_vectors.json"

func seq32(first byte) []byte {
	b := make([]byte, 32)
	for i := range b {
		b[i] = first + byte(i)
	}
	return b
}

func buildRelayVectors(t *testing.T) map[string]any {
	t.Helper()
	must := func(err error) {
		t.Helper()
		if err != nil {
			t.Fatal(err)
		}
	}
	supSeed, devSeed, supEncRaw, devEncRaw := seq32(0x01), seq32(0x21), seq32(0x41), seq32(0x61)
	sup, dev := ed25519.NewKeyFromSeed(supSeed), ed25519.NewKeyFromSeed(devSeed)
	supPub, devPub := sup.Public().(ed25519.PublicKey), dev.Public().(ed25519.PublicKey)
	sid, did := envelope.DeviceID(supPub), envelope.DeviceID(devPub)
	supEnc, err := ecdh.X25519().NewPrivateKey(supEncRaw)
	must(err)
	devEnc, err := ecdh.X25519().NewPrivateKey(devEncRaw)
	must(err)
	supEncPub, devEncPub := envelope.B64URL(supEnc.PublicKey().Bytes()), envelope.B64URL(devEnc.PublicKey().Bytes())
	const ts, exp = int64(1790850000000), int64(1790850300000)

	// section 7: the box key, the same from both ends
	shared, err := supEnc.ECDH(devEnc.PublicKey())
	must(err)
	salt := sha256.Sum256([]byte(sid + did))
	key, err := relaylink.BoxKey(supEnc, devEnc.PublicKey(), sid, did)
	must(err)

	// a msg frame supervisor → device
	cardDone := `{"id":"wd-00112233445566778899aabbccddeeff","outcome":"approved"}`
	msgID, msgNonce := "000102030405060708090a0b0c0d0e0f", bytes.Repeat([]byte{0xa0}, 24)
	msgAAD, err := relaylink.AAD(msgID, sid, did, "card.done", exp)
	must(err)
	msgBody, err := relaylink.Seal(key, msgNonce, []byte(cardDone), msgAAD)
	must(err)

	// section 3: the signed hello of both roles
	hello := func(role string, priv ed25519.PrivateKey, pub ed25519.PublicKey, enc, name string) map[string]any {
		client := map[string]any{"name": name, "version": "1.0.0", "protocol": relayProtocol}
		nonce := envelope.B64URL(seq32(0x80))
		s, err := envelope.Canonical(map[string]any{"type": relaylink.HelloType, "role": role, "key": envelope.B64URL(pub), "enc": enc, "ts": ts, "nonce": nonce, "client": client})
		must(err)
		return map[string]any{"signingString": string(s), "frame": map[string]any{"type": "hello", "role": role, "key": envelope.B64URL(pub), "enc": enc, "ts": ts,
			"nonce": nonce, "client": client, "sig": envelope.B64URL(ed25519.Sign(priv, s))}}
	}

	// section 6: the pairing request and its pair frame
	pp := envelope.PairPayload{Code: "K7Q4M2XD", DeviceID: did, Pubkey: envelope.B64URL(devPub), Enc: devEncPub, Name: "Test phone", SupervisorID: sid, Ts: ts,
		Nonce: "5b8e2f0a-1c3d-4e5f-8a9b-0c1d2e3f4a5b"}
	pairSS, err := envelope.PairSigningString(pp)
	must(err)
	pairPT, err := json.Marshal(map[string]any{"payload": pp, "signature": envelope.B64URL(ed25519.Sign(dev, pairSS))})
	must(err)
	pairID, pairNonce := "f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff", bytes.Repeat([]byte{0xb0}, 24)
	pairAAD, err := relaylink.AAD(pairID, did, sid, "pair", exp)
	must(err)
	pairBox, err := relaylink.Seal(key, pairNonce, pairPT, pairAAD)
	must(err)
	boxRaw, _ := envelope.DecodeB64URL(pairBox)
	pairBody := envelope.B64URL(append(devEnc.PublicKey().Bytes(), boxRaw...))

	cardSS, err := relaylink.CardSigningString("wd-00112233445566778899aabbccddeeff", hex.EncodeToString(seq32(0xc0)), ts, exp)
	must(err)
	link := envelope.PairLink{Relay: "wss://relay.wardenclaw.dev/v1/ws", SID: sid, Key: envelope.B64URL(supPub), Enc: supEncPub, Code: pp.Code, Host: "agent-host"}

	return map[string]any{
		"note": "generated by `WARDEN_UPDATE_VECTORS=1 go test -run TestRelayVectors .` in daemon/; spec: protocol/RELAY.md. " +
			"hex members are raw bytes in hex, all other binary is base64url without padding. signingString and aad are the exact UTF-8 bytes that are signed / authenticated.",
		"supervisor": map[string]any{"seed": hex.EncodeToString(supSeed), "key": envelope.B64URL(supPub), "id": sid,
			"encPrivate": hex.EncodeToString(supEncRaw), "enc": supEncPub},
		"device": map[string]any{"seed": hex.EncodeToString(devSeed), "key": envelope.B64URL(devPub), "id": did,
			"encPrivate": hex.EncodeToString(devEncRaw), "enc": devEncPub},
		"boxKey": map[string]any{
			"note":   "shared = X25519(my encPrivate, their enc); salt = sha256(utf8(supervisor.id + device.id)); key = HKDF-SHA256(ikm shared, salt, info, 32 bytes). One key per (supervisor, device), both directions.",
			"shared": hex.EncodeToString(shared), "salt": hex.EncodeToString(salt[:]), "info": relaylink.BoxInfo, "key": hex.EncodeToString(key)},
		"msg": map[string]any{
			"note":  "body = b64url(nonce(24) || XChaCha20-Poly1305(boxKey.key, nonce, utf8(plaintext), utf8(aad))); aad = canonicalJson({type, id, from, to, kind, exp}) of the frame as the receiver sees it (from is set by the relay).",
			"frame": map[string]any{"type": "msg", "id": msgID, "from": sid, "to": did, "seq": 7, "ts": ts, "exp": exp, "kind": "card.done", "body": msgBody},
			"aad":   string(msgAAD), "nonce": hex.EncodeToString(msgNonce), "plaintext": cardDone},
		"push": map[string]any{
			"note": "What a notification carries of msg.frame when the device is offline (RELAY.md section 8): apns is the `relay` member of the APNs payload, fcm the data of the FCM message (all strings, exp in decimal). " +
				"The receiver rebuilds the aad from the notification alone: canonicalJson({type, id, from: sid, to, kind, exp}), equal to msg.aad, and opens body with boxKey.key.",
			"apns": map[string]any{"sid": sid, "id": msgID, "to": did, "kind": "card.done", "exp": exp, "body": msgBody},
			"fcm":  map[string]any{"sid": sid, "id": msgID, "to": did, "kind": "card.done", "exp": strconv.FormatInt(exp, 10), "body": msgBody}},
		"hello": map[string]any{
			"note":       "sig = Ed25519(identity key, utf8(signingString)); nonce is the relay's challenge nonce.",
			"supervisor": hello("supervisor", sup, supPub, supEncPub, "wardend"),
			"device":     hello("device", dev, devPub, devEncPub, "wardenclaw-app")},
		"pair": map[string]any{
			"note": "A pair frame only: body = b64url(device.enc raw (32) || nonce(24) || ciphertext). The box is the one of msg (same boxKey, aad with kind \"pair\" and from = device.id). " +
				"plaintext = {payload, signature}; signature = Ed25519(device identity key, utf8(signingString)), signingString = canonicalJson({type:\"wardenclaw.pair.v1\", ...payload}). " +
				"The supervisor refuses the frame unless payload.enc equals the 32 bytes in front of the body and payload.deviceId equals from.",
			"payload": pp, "signingString": string(pairSS), "signature": envelope.B64URL(ed25519.Sign(dev, pairSS)), "plaintext": string(pairPT),
			"frame": map[string]any{"type": "pair", "id": pairID, "from": did, "to": sid, "seq": 1, "ts": ts, "exp": exp, "kind": "pair", "body": pairBody},
			"aad":   string(pairAAD), "nonce": hex.EncodeToString(pairNonce), "fingerprint": envelope.Fingerprint(did)},
		"card": map[string]any{
			"note": "supervisorSig of a card = Ed25519(supervisor identity key, utf8(signingString)), signingString = canonicalJson({type:\"wardenclaw.card.v1\", id, digest, createdAt, expiresAt}).",
			"id":   "wd-00112233445566778899aabbccddeeff", "digest": hex.EncodeToString(seq32(0xc0)), "createdAt": ts, "expiresAt": exp,
			"signingString": string(cardSS), "supervisorSig": envelope.B64URL(ed25519.Sign(sup, cardSS))},
		"link": map[string]any{"text": link.String(), "v": 2, "relay": link.Relay, "sid": link.SID, "key": link.Key, "enc": link.Enc, "code": link.Code, "host": link.Host},
	}
}

func mustAAD(t *testing.T, id, from, to, kind string, exp int64) []byte {
	t.Helper()
	a, err := relaylink.AAD(id, from, to, kind, exp)
	if err != nil {
		t.Fatal(err)
	}
	return a
}

func TestRelayVectors(t *testing.T) {
	b, _ := json.MarshalIndent(buildRelayVectors(t), "", "  ")
	b = append(b, '\n')
	if os.Getenv("WARDEN_UPDATE_VECTORS") != "" {
		if err := os.WriteFile(relayVectorsPath, b, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	ref, err := os.ReadFile(relayVectorsPath)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(ref, b) {
		t.Fatalf("%s is stale: run with WARDEN_UPDATE_VECTORS=1", relayVectorsPath)
	}

	// from here on only the file: what a client implemented against it would do
	type party struct{ Seed, Key, ID, EncPrivate, Enc string }
	type frame struct {
		ID, From, To, Kind, Body string
		Exp                      int64
	}
	var v struct {
		Supervisor, Device party
		BoxKey             struct{ Key string }
		Msg                struct {
			Frame          frame
			AAD, Plaintext string
		}
		Push struct {
			APNs struct {
				SID, ID, To, Kind, Body string
				Exp                     int64
			}
			FCM map[string]string
		}
		Hello map[string]json.RawMessage
		Pair  struct {
			Payload                             envelope.PairPayload
			SigningString, Signature, Plaintext string
			Frame                               frame
		}
		Card struct{ SigningString, SupervisorSig string }
		Link struct{ Text string }
	}
	if err := json.Unmarshal(ref, &v); err != nil {
		t.Fatal(err)
	}
	priv := func(h string) *ecdh.PrivateKey {
		raw, _ := hex.DecodeString(h)
		k, err := ecdh.X25519().NewPrivateKey(raw)
		if err != nil {
			t.Fatal(err)
		}
		return k
	}
	supEnc, devEnc := priv(v.Supervisor.EncPrivate), priv(v.Device.EncPrivate)
	supPub, _ := envelope.DecodeKey(v.Supervisor.Key)
	devPub, _ := envelope.DecodeKey(v.Device.Key)
	devEncPub, err := relaylink.ParseEncKey(v.Device.Enc)
	if err != nil || envelope.DeviceID(supPub) != v.Supervisor.ID || envelope.DeviceID(devPub) != v.Device.ID {
		t.Fatalf("keys: %v", err)
	}

	// the device opens the supervisor's msg with its own private key
	supEncPub, _ := relaylink.ParseEncKey(v.Supervisor.Enc)
	key, err := relaylink.BoxKey(devEnc, supEncPub, v.Supervisor.ID, v.Device.ID)
	if err != nil || hex.EncodeToString(key) != v.BoxKey.Key {
		t.Fatalf("box key from the device side: %x %v", key, err)
	}
	aad, _ := relaylink.AAD(v.Msg.Frame.ID, v.Msg.Frame.From, v.Msg.Frame.To, v.Msg.Frame.Kind, v.Msg.Frame.Exp)
	if string(aad) != v.Msg.AAD {
		t.Fatalf("aad %s", aad)
	}
	if pt, err := relaylink.Open(key, v.Msg.Frame.Body, aad); err != nil || string(pt) != v.Msg.Plaintext {
		t.Fatalf("msg: %q %v", pt, err)
	}

	// a notification alone: the aad from its members, the box opens (APNs: exp a number, FCM: a string)
	n := v.Push.APNs
	fcmExp, _ := strconv.ParseInt(v.Push.FCM["exp"], 10, 64)
	for name, a := range map[string][]byte{
		"apns": mustAAD(t, n.ID, n.SID, n.To, n.Kind, n.Exp),
		"fcm":  mustAAD(t, v.Push.FCM["id"], v.Push.FCM["sid"], v.Push.FCM["to"], v.Push.FCM["kind"], fcmExp),
	} {
		body := n.Body
		if name == "fcm" {
			body = v.Push.FCM["body"]
		}
		if pt, err := relaylink.Open(key, body, a); err != nil || string(pt) != v.Msg.Plaintext || string(a) != v.Msg.AAD {
			t.Fatalf("push %s: %q %v", name, pt, err)
		}
	}

	// the supervisor opens the pair frame as the client does, and the payload is bound to it
	e := relaylink.Envelope{Type: "pair", ID: v.Pair.Frame.ID, From: v.Pair.Frame.From, To: v.Pair.Frame.To, Kind: v.Pair.Frame.Kind, Exp: v.Pair.Frame.Exp, Body: v.Pair.Frame.Body}
	pt, enc, err := relayOpenPair(supEnc, v.Supervisor.ID, e)
	if err != nil || string(pt) != v.Pair.Plaintext || enc != v.Device.Enc || enc != v.Pair.Payload.Enc || v.Pair.Payload.DeviceID != e.From {
		t.Fatalf("pair frame: %q %q %v", pt, enc, err)
	}
	ss, _ := envelope.PairSigningString(v.Pair.Payload)
	if string(ss) != v.Pair.SigningString || !envelope.VerifySig(devPub, ss, v.Pair.Signature) {
		t.Fatalf("pair signing string %s", ss)
	}
	e.From = v.Supervisor.ID // a relay that rewrites a routing member: the box does not open
	if _, _, err := relayOpenPair(supEnc, v.Supervisor.ID, e); err == nil {
		t.Fatal("a pair frame with another from opened")
	}
	if k, err := relaylink.BoxKey(supEnc, devEncPub, v.Supervisor.ID, v.Device.ID); err != nil || hex.EncodeToString(k) != v.BoxKey.Key {
		t.Fatalf("box key from the supervisor side: %x %v", k, err)
	}

	for role, pub := range map[string]ed25519.PublicKey{"supervisor": supPub, "device": devPub} {
		var h struct {
			SigningString string
			Frame         struct{ Sig string }
		}
		if err := json.Unmarshal(v.Hello[role], &h); err != nil || !envelope.VerifySig(pub, []byte(h.SigningString), h.Frame.Sig) {
			t.Fatalf("hello of the %s: %v", role, err)
		}
	}
	if !envelope.VerifySig(supPub, []byte(v.Card.SigningString), v.Card.SupervisorSig) {
		t.Fatal("card signature")
	}
	if l, err := envelope.ParsePairLink(v.Link.Text); err != nil || l.Relay == "" || l.SID != v.Supervisor.ID || l.Enc != v.Supervisor.Enc {
		t.Fatalf("link: %+v %v", l, err)
	}
}
